config/routes.rb
Turnrelay::Application.routes.draw do

  devise_for :users

  resources  :users, only: [:show, :edit, :update] do
    resources :allocations, only: [:show]
  end
 
  resources  :messages, only: [:new, :create]

  root :to => 'site#home'

  match '/help',      to:'site#help'
  match '/features',  to:'site#features'
  match '/pricing',   to:'site#pricing'
  match '/blog',      to:'site#blog'

  match '/contact',   to:'messages#new'
  match '/about',     to:'site#about'

  match '/privacy',   to:'site#privacy'
  match '/terms',     to:'site#terms'

end

app/models/allocation.rb
class Allocation < ActiveRecord::Base
  attr_accessible :alloc_at, :allotted_lifetime, :bandwidth_used, :dealloc_at, :realm, :req_lifetime, :username

  # association with the user model
  belongs_to :user

  # some validations
  validates :user_id, presence: true
  validates :username, presence: true
  validates :realm, presence: true

  default_scope order: 'allocations.created_at DESC'
end

app/models/message.rb
class Message

  include ActiveAttr::Model

  attribute :name
  attribute :email
  attribute :content

  attr_accessible :name, :email, :content

  validates_presence_of :name
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :content
  validates_length_of :content, :maximum => 500

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :max_allocs, :max_concur_allocs, :realm, :username, :turn_secret
  attr_accessible :def_lifetime, :max_bandwidth
  attr_accessible :first_name, :last_name
  
  # association with the allocations model
  has_many :allocations, dependent: :destroy

  validates_uniqueness_of :username, :scope => :realm, :on => :update

  #def to_param
  #  [id, first_name.parameterize, last_name.parameterize].join("-")
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    sign_in_url = url_for(:action => 'new', :controller => 'sessions', :only_path => false, :protocol => 'http')
    #logger.fatal "This is the sign in url: #{sign_in_url}"
    if request.referer == sign_in_url
      #logger.fatal "Yeah! this is sign in url"
      user_path(current_user)
      # super
    else
      #logger.fatal "This is the user path: #{current_user} : #{user_url(current_user)}"
      #logger.fatal "This is the stored resource path: #{stored_location_for(resource)}"
      #logger.fatal "This is the referrer path: #{request.referrer}"
      user_url(resource) || stored_location_for(resource) || request.referer
    end
  end
  
  # This is basically to identify/debug who has triggered a redirect_to
  def redirect_to(options = {}, response_status = {})
    ::Rails.logger.error("Redirected by #{caller(1).first rescue "unknown"}")
    super(options, response_status)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      ContactusMailer.new_message(@message).deliver
      redirect_to root_url, notice: "Message sent! Thank you for contacting us."
    else
      flash.now.alert = "Please fill all the fields."
      render "new"
    end
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    if user_signed_in?
      redirect_to user_path(current_user)
    end
  end

  def help
  end

  def features
  end

  def blog
  end

  def signin
  end

  def about
  end

  def privacy
  end

  def terms
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    # @user = User.find(params[:id])
    @user = current_user
  end

  def edit
    # @user = User.find(params[:id])
    @user = current_user
  end

  def update
    # @user = User.find(params[:id])
    @user = current_user
    if @user.update_attributes(params[:user])
      # handle a successful update
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      # print the errors to the development log
      Rails.logger.info(@user.errors.messages.inspect)
      flash[:error] = "Something wrong? Profile NOT updated"
      render 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/site_helper.rb
module SiteHelper

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/allocations/_allocation.html.erb
<li>
<span><%= allocation.username %><%= allocation.alloc_at %></span>
</li>

app/views/layouts/_allocation_table.html.erb
<% if @user.allocations.any? %>

<table id="allocations" class="table table-striped table-bordered table-hover">
<thead>
  <tr>
    <th>No</th>
    <th>Allocated at</th>
    <th>Deallocated at</th>
    <th>Ingress Bandwidth</th>
    <th>Egress Bandwidth</th>
    <th>Total Bandwidth Bytes</th>
    <th>Protocol</th>
    <th>Status</th>
  </tr>
</thead>

<% i = 0 %>
<tbody>
  <% @user.allocations.each do |allocation| %>
  <% i += 1 %>
  <tr>
    <td><%= i %></td>
    <td><%= allocation.alloc_at %></td>
    <td><%= allocation.dealloc_at %></td>
    <td><%= allocation.ingress_data %></td>
    <td><%= allocation.egress_data %></td>
    <td><%= allocation.total_relay %></td>
    <td><%= allocation.protocol %></td>
    <td><%= if allocation.dealloc_at.blank? 
                'Active' 
            else 
                'Deallocated' 
            end %></td>
  </tr>
  <% end %>
</tbody>

</table>
<% else %>
  <p>Howdy, no allocations so far!.</p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">

<div class="navbar-inner navbar">
  <div class="container" style="height:60p;">
    <div class="nav-collapse">
      <ul class="nav pull-right" style="margin-top:8px">
        <li><%= link_to "Privacy", privacy_path %></li>
        <li><%= link_to "Terms of Service", terms_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
      <center>
        <span class="muted span6 offset1" style="margin-top:16px;"><small>
              Designed and built by MindBricks Technologies &copy; 2009-2013 All Rights Reserved
      </small></span>
      </center>
    </div>
  </div>
</div>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar transparent navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand">
        <%= link_to "SeamConnect", root_path, id: "logo" %>
      </a>
      <nav>
        <ul class="nav">
          <li><%= link_to "Features", features_path %></li>
          <li><%= link_to "Service Providers", features_path %></li>
          <li><%= link_to "Enterprises", features_path %></li>
          <li><%= link_to "Blog",     blog_path %></li>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.email, '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Change Password", edit_user_registration_path %></li>
                <li><%= link_to "TURN Configuration", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Delete Account", registration_path(current_user), :confirm => "Are you sure?", :method => :delete %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
              </ul>
            </li>
            <li><!-- <i class="icon-user icon-white"></i> -->
            <%= link_to "Sign Out",  
                destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><!-- <i class="icon-user icon-white"></i> -->
            <%= link_to "Sign In",  new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_signin.html.erb
<%= form_for(resource, :html => { :class => "form" }, :as => resource_name, :url => session_path(resource_name)) do |f| %>

  <fieldset>
    <legend> Sign In </legend>

    <div class="control-group">

      <!-- Text input-->
      <label class="control-label" for="user_email">Email address</label>
      <div class="controls">
        <input id="user_email" name="user[email]" autofocus="autofocus" placeholder="Your email address" class="input-xlarge" type="text">
        <p class="help-block"></p>
      </div>
    </div>

    <div class="control-group">

      <!-- Text input-->
      <label class="control-label" for="user_password">Password</label>
      <div class="controls">
        <input id="user_password" name="user[password]" placeholder="password" class="input-xlarge" type="password">
        <p class="help-block"></p>
      </div>
    </div>

    <div class="control-group">

      <!-- Checkboxes-->
      <label class="control-label"></label>
      <div class="controls">
        <label class="checkbox">
          <input id="user_remember_me" name="user[remember_me]" type="checkbox">Remember me
        </label>
        <p class="help-block"></p>
      </div>

    </div>

    <div class="control-group">
      <label class="control-label"></label>

      <!-- Button -->
      <div class="controls">
        <div><%= f.submit "Sign me in", class: "btn btn-small btn-success" %></div>
      </div>
    </div>

  </fieldset>

<% end %>

<%= render "devise/shared/links" %>

app/views/layouts/_signup.html.erb
<%= form_for(resource, :html => { :class => "form-horizontal" }, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <fieldset>
  <div class="control-group">

    <!-- Text input-->
    <label class="control-label" for="user_email"></label>
    <div class="controls">
      <input id="user_email" name="user[email]" autofocus="autofocus" placeholder="Your email address" class="input-xlarge" type="text">
      <p class="help-block"></p>
    </div>
  </div>

  <div class="control-group">

    <!-- Text input-->
    <label class="control-label" for="user_password"></label>
    <div class="controls">
      <input id="user_password" name="user[password]" placeholder="password" class="input-xlarge" type="password">
      <p class="help-block"></p>
    </div>
  </div>

  <div class="control-group">

    <!-- Text input-->
    <label class="control-label" for="user_password_confirmation"></label>
    <div class="controls">
      <input id="user_password_confirmation" name="user[password_confirmation]" placeholder="confirm password" class="input-xlarge" type="password">
    </div>
  </div>

  <div class="control-group">
    <!-- Terms and Privacy text -->
    <label class="control-label"></label>
    <div class="controls">
        <p class="help-block"><h6>By clicking on "Sign up for free" below, you agree to the <%= link_to "Terms of Service", terms_path %> and the <%= link_to "Privacy", privacy_path %> Policy.</h6></p>
    </div>

    <label class="control-label"></label>

    <!-- Button -->
    <div class="controls">
      <%= f.submit "Sign up for free", class: "btn btn-success mb-home-signup-large" %>
    </div>
  </div>

  </fieldset>
</form>
<% end %>

app/views/layouts/_user_home.html.erb
<p class="lead">User: <%= @user.email %></p>
<p class="text-info"> Number of Allocations: <%= @user.allocations.count %> </p>
<p class="text-info"> Configured Max Allocations: <%= @user.max_allocs %> </p>
<p class="text-info"> Configured Max Concurrent Allocations: <%= @user.max_concur_allocs %> </p>
<p class="text-info"> Realm: <%= @user.realm %> </p>
<p class="text-info"> Default Lifetime : <%= @user.def_lifetime %> </p>
<p class="text-info"> Maximum Bandwidth : <%= @user.max_bandwidth %> </p>
<p class="text-info"> TURN username : <%= @user.username %> </p>
<hr />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>SeamConnect * <%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Arvo", :media => "all" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Le fav and touch icons -->
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="apple-touch-icon" href="twitter-bootstrap-v2/docs/examples/images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="twitter-bootstrap-v2/docs/examples/images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="twitter-bootstrap-v2/docs/examples/images/apple-touch-icon-114x114.png">
  </head>
  <body>
    <div id="mywrap">
      <div id="container">
      <%= render 'layouts/messages' %>
      <%= render 'layouts/header' %>
      <div class="container-fluid">
        <div class="row-fluid">
          <%= yield %>
        </div>
      </div>
      <div id="mypush"></div>
      </div>
    </div>
    <div id="myfooter">
      <%= render 'layouts/footer' %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/messages/new.html.erb
<h1>Contact Us</h1>

<%= form_for @message do |f| %>
  <% if @message.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :content, "Message" %><br />
    <%= f.text_area :content, :rows => 5 %>
  </div>
  <div class="actions"><%= f.submit "Send Message" %></div>
<% end %>

app/views/site/about.html.erb
<% provide(:title, 'Features') %>
<h1>MindBricks NAT Server About</h1>
<p>
<a href="http://www.mindbricks.com">MindBricks</a> NAT server aids in NAT 
traversal for all the client commiunication needs.
</p>

app/views/site/blog.html.erb
<% provide(:title, 'Features') %>
<h1>MindBricks NAT Server Blog</h1>
<p>
<a href="http://www.mindbricks.com">MindBricks</a> NAT server aids in NAT 
traversal for all the client commiunication needs.
</p>

app/views/site/contact.html.erb
<% provide(:title, 'Features') %>
<h1>MindBricks NAT Server Contact</h1>
<p>
<a href="http://www.mindbricks.com">MindBricks</a> NAT server aids in NAT 
traversal for all the client commiunication needs.
</p>

app/views/site/features.html.erb
<% provide(:title, 'Features') %>
<h1>MindBricks NAT Server Features</h1>
<p>
<a href="http://www.mindbricks.com">MindBricks</a> NAT server aids in NAT 
traversal for all the client commiunication needs.
</p>

app/views/site/help.html.erb
<% provide(:title, 'Help') %>
<h1>MindBricks NAT Server Help</h1>
<p>
<a href="http://www.mindbricks.com">MindBricks</a> NAT server aids in NAT 
traversal for all the client commiunication needs.
</p>

app/views/site/home.html.erb
<% provide(:title, 'Seamless Communication and Collaboration') %>
<div>
  <div class="span12">
  <div class="hero-unit">
    <div class="row user-nav">
      <div class="span7">
        <h1>Seamless communication and collaboration</h1>
        <p>NAT traversal service on cloud. For all IP based communications and collaboration - Webrtc, Video calling, Messaging, conferencing and more.</p>
        <!-- <p><center><a href="users/sign_up" class="btn btn-primary btn-large">Sign up for free &raquo;</a></center></p> -->
      </div>
      <div class="span3">
        <%= render 'layouts/signup' %>
      </div>
    </div>  
  </div>
  </div>

  <div class="row">
    <div class="span4">
      <img class="img-circle" data-src="holder.js/140x140">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>
      <p><a class="btn" href="http://twitter.github.com/bootstrap/examples/carousel.html#">View details »</a></p>
    </div><!-- /.span4 -->
    <div class="span4">
      <img class="img-circle" data-src="holder.js/140x140">
      <h2>Heading</h2>
      <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <p><a class="btn" href="http://twitter.github.com/bootstrap/examples/carousel.html#">View details »</a></p>
    </div><!-- /.span4 -->
    <div class="span4">
      <img class="img-circle" data-src="holder.js/140x140">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <p><a class="btn" href="http://twitter.github.com/bootstrap/examples/carousel.html#">View details »</a></p>
    </div><!-- /.span4 -->
  </div><!-- /.row -->

</div>

app/views/site/pricing.html.erb
<% provide(:title, 'Pricing') %>
<h1>MindBricks NAT Server Pricing </h1>
<p>
<a href="http://www.mindbricks.com">MindBricks</a> NAT server aids in NAT 
traversal for all the client commiunication needs.
</p>

app/views/site/privacy.html.erb
<% provide(:title, 'Privacy') %>
<h3>MindBricks Privacy Policy</h3>

<p>This Privacy Policy governs the manner in which MindBricks Pvt Ltd collects, uses, maintains and discloses information collected from users (each, a "User") of the facetimes.com website ("Site"). This privacy policy applies to the Site and all products and services offered by MindBricks Pvt Ltd.</p>

<b>Personal identification information</b>

<p>We may collect personal identification information from Users in a variety of ways, including, but not limited to, when Users visit our site, register on the site, place an order, fill out a form, and in connection with other activities, services, features or resources we make available on our Site. Users may be asked for, as appropriate, name, email address, mailing address, phone number, credit card information. We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain Site related activities.</p>

<b>Non-personal identification information</b>

<p>We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, the type of computer and technical information about Users means of connection to our Site, such as the operating system and the Internet service providers utilized and other similar information.</p>

<b>Web browser cookies</b>

<p>Our Site may use "cookies" to enhance User experience. User's web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.</p>

<b>How we use collected information</b>

<p>MindBricks Pvt Ltd may collect and use Users personal information for the following purposes:

    - To improve customer service
    Information you provide helps us respond to your customer service requests and support needs more efficiently.
    - To personalize user experience
    We may use information in the aggregate to understand how our Users as a group use the services and resources provided on our Site.
    - To process payments
    We may use the information Users provide about themselves when placing an order only to provide service to that order. We do not share this information with outside parties except to the extent necessary to provide the service.
    - To send periodic emails
    We may use the email address to send User information and updates pertaining to their order. It may also be used to respond to their inquiries, questions, and/or other requests. If User decides to opt-in to our mailing list, they will receive emails that may include company news, updates, related product or service information, etc. If at any time the User would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email or User may contact us via our Site.</p>

<b>How we protect your information</b>

<p>We adopt appropriate data collection, storage and processing practices and security measures to protect against unauthorized access, alteration, disclosure or destruction of your personal information, username, password, transaction information and data stored on our Site.</p>

<p>Sensitive and private data exchange between the Site and its Users happens over a SSL secured communication channel and is encrypted and protected with digital signatures.</p>

<b>Sharing your personal information</b>

<p>We do not sell, trade, or rent Users personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates and advertisers for the purposes outlined above.We may use third party service providers to help us operate our business and the Site or administer activities on our behalf, such as sending out newsletters or surveys. We may share your information with these third parties for those limited purposes provided that you have given us your permission.</p>

<b>Changes to this privacy policy</b>

<p>MindBricks Pvt Ltd has the discretion to update this privacy policy at any time. When we do, we will revise the updated date at the bottom of this page and send you an email. We encourage Users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect. You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications.</p>

<b>Your acceptance of these terms</b>

<p>By using this Site, you signify your acceptance of this policy. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes.</p>

<b>Contacting us</b>

<p>If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this site, please contact us at:</p>
MindBricks Pvt Ltd
facetimes.com
Office no-4, 5th floor, Sapphire Business Center, Opp. Hotel Kanak Comfort, Ushmanpura, Ahmedabad - 380013
079-39412345
privacy@mindbricks.com

<p></p>
<p>This document was last updated on March 30, 2013</p>

app/views/site/terms.html.erb
<% provide(:title, 'Terms') %>
<h1>MindBricks NAT Server Terms of Service</h1>
<p>
<a href="http://www.mindbricks.com">MindBricks</a> NAT server aids in NAT 
traversal for all the client commiunication needs.
</p>

app/views/users/edit.html.erb
<%= form_for(@user, :html => { :class => "form-horizontal" }, :url => { :action => "update" }, :method => "put") do |f| %>

  <fieldset>
    <div id="legend" class="">
      <legend class="">Account Settings</legend>
    </div>

    <!-- <%= debug f %> -->
    <!-- <%= simple_format @user.to_yaml %> -->

    <div class="control-group">

      <!-- Text input-->
      <%= f.label :first_name, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :first_name, :class => "input-xlarge" %>
        <p class="help-block"></p>
      </div>
    </div>

    <div class="control-group">

      <!-- Text input-->
      <%= f.label :last_name, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :last_name, :class => "input-xlarge" %>
        <p class="help-block"></p>
      </div>
    </div>

    <div class="control-group">

      <!-- Text input-->
      <%= f.label :username, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :username, :class => "input-xlarge" %>
        <p class="help-block"><small>Used during TURN protocol exchange</small></p>
      </div>
    </div>
      
    <div class="control-group">

      <!-- Text input-->
      <%= f.label :turn_secret, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :turn_secret, :class => "input-xlarge" %>
        <p class="help-block"><small>Used during TURN protocol exchange. Must be atleast 8 chars.</small></p>
      </div>
    </div>
      
    <div class="control-group">

      <!-- Text input-->
      <%= f.label :max_concur_allocs, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :max_concur_allocs, :class => "input-xlarge" %>
        <p class="help-block"><small>Maximum allowed concurrent/active allocations at any time.</small></p>
      </div>
    </div>


    <div class="control-group">

      <!-- Text input-->
      <%= f.label :realm, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :realm, :class => "input-xlarge" %>
        <p class="help-block"></p>
      </div>
    </div>

    <div class="control-group">

      <!-- Text input-->
      <%= f.label :def_lifetime, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :def_lifetime, :class => "input-xlarge" %>
        <p class="help-block"><small>Default lifetime of the allocation in seconds if one is not given.</small></p>
      </div>
    </div>

    <div class="control-group">

      <!-- Text input-->
      <%= f.label :max_bandwidth, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :max_bandwidth, :class => "input-xlarge" %>
        <p class="help-block"><small>Maximum allowed bandwidth.</small></p>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label"></label>

      <!-- Button -->
      <div class="controls">
        <div><%= f.submit "Save Configuration", class: "btn btn-small btn-success" %></div>
      </div>
    </div>

  </fieldset>
</form>
<% end %>

app/views/users/show.html.erb
<br />
<br />
<!-- <hr /> -->

<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-pills">
    <li class="active"><a href="#user_home" data-toggle="tab">Account Home</a></li>
    <li><a href="#user_alloc_list" data-toggle="tab">Allocation List</a></li>
    <li><a href="#user_payments" data-toggle="tab">Payment History</a></li>
    <li><a href="#user_service_reqs" data-toggle="tab">Service Requests</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="user_home">
      <%= render 'layouts/user_home' %>
    </div>
    <div class="tab-pane" id="user_alloc_list">
      <%= render 'layouts/allocation_table' %>
    </div>
    <div class="tab-pane" id="user_payments">
      <p>Howdy, no past payments history!.</p>
    </div>
    <div class="tab-pane" id="user_service_reqs">
      <p>Howdy, no service requests here!.</p>
    </div>
  </div>
</div>

<hr />